-- ============================================================
-- SEFE · INSTALADOR DE BASE PARA UN CLIENTE NUEVO
-- ============================================================
-- ⚠️ ARCHIVO GENERADO — NO EDITAR A MANO.
--    Se arma con: node scripts/build-instalador.js
--    (junta todas las migraciones de supabase/migrations/).
--
-- QUÉ ES: todo lo que necesita la base de un cliente nuevo, en
-- una sola pegada. Tablas, seguridad (RLS capa 1 y 2), índices y
-- secuencias. Reemplaza correr las 16 migraciones una por una.
--
-- CÓMO SE USA (una sola vez, en la base NUEVA y VACÍA del cliente):
--   1. Crear el proyecto en Supabase (queda vacío).
--   2. Abrir SQL Editor → New query.
--   3. Pegar TODO este archivo y Run.
--   4. Al final deben verse las tablas creadas, sin errores.
--
-- Es idempotente: si se corre de más, no rompe nada.
-- Incluye 16 migraciones, en este orden:
--   01. 20260101000000_baseline_esquema.sql
--   02. 20260805000000_base_historico.sql
--   03. 20260812024415_realtime.sql
--   04. 20260812030419_rls.sql
--   05. 20260819120000_sede_documento.sql
--   06. 20260820130000_creditos_cliente.sql
--   07. 20260820160000_costo_historico_documento.sql
--   08. 20260825120000_indices_reportes.sql
--   09. 20260825140000_correlativos_secuencias.sql
--   10. 20260829120000_conciliado_banco.sql
--   11. 20260829140000_conciliaciones.sql
--   12. 20260829160000_empleados.sql
--   13. 20260829170000_rls_tablas_nuevas.sql
--   14. 20260829180000_planillas.sql
--   15. 20260830100000_ctrl_ambientales.sql
--   16. 20260831120000_rls_capa2.sql
-- ============================================================


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260101000000_baseline_esquema.sql                     ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- BASELINE — el esquema completo de SEFE, creado desde cero.
-- ============================================================
-- Esta es la PRIMERA migración: crea todas las tablas, llaves,
-- relaciones e índices de una base vacía. Va antes que
-- base_historico y que todas las demás.
--
-- ── PARA QUÉ SIRVE ──────────────────────────────────────────
-- Para dar de alta un CLIENTE NUEVO: se crea un proyecto Supabase
-- vacío y, al correr las migraciones, esto arma toda la estructura.
-- Después, base_historico y las demás migraciones agregan lo que
-- vino evolucionando — pero como todas usan "if not exists", en una
-- base recién creada por este baseline simplemente no repiten nada.
--
-- ── EN PRODUCCIÓN Y PRUEBAS (bases que YA existen) ──────────
-- Es un NO-OP total. Todo está con "create table if not exists" /
-- "create index if not exists", así que no toca ni una tabla ni un
-- dato: sólo queda registrada como aplicada. La estructura de esas
-- bases ya está desde hace meses.
--
-- ── NOTAS ───────────────────────────────────────────────────
-- · Los id son IDENTITY (los genera Postgres), tal como en la base
--   real: 'always' donde el cliente nunca los manda, 'by default'
--   donde a veces sí.
-- · Las tablas de respaldo (_bkp_*) NO van: son de una limpieza
--   puntual, no parte del sistema.
-- · Las políticas RLS y el tiempo real los agregan sus propias
--   migraciones (rls / realtime), que corren después de ésta.
-- ============================================================


-- ── Catálogos base (sin dependencias) ───────────────────────
create table if not exists public.vendedores (
  id      bigint generated always as identity primary key,
  nombre  text not null,
  activo  boolean default true,
  creado  timestamptz default now()
);

create table if not exists public.pilotos (
  id      bigint generated always as identity primary key,
  nombre  text not null,
  activo  boolean default true,
  creado  timestamptz default now()
);

create table if not exists public.proveedores (
  id           bigint generated always as identity primary key,
  nombre       text not null,
  razon_social text,
  nit          text,
  telefono     text,
  correo       text,
  dias_credito integer default 0,
  activo       boolean default true,
  creado       timestamptz default now()
);

create table if not exists public.cuentas_banco (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  banco         text,
  numero        text,
  tipo          text default 'monetaria'::text,
  moneda        text default 'GTQ'::text,
  saldo_inicial numeric default 0,
  activo        boolean default true,
  creada        timestamptz default now()
);

create table if not exists public.categorias (
  nombre       text not null primary key,
  umbral_stock numeric not null default 10
);

create table if not exists public.productos (
  id                bigint generated always as identity primary key,
  codigo            text not null,
  nombre            text not null,
  precio            numeric(12,2) default 0,
  costo             numeric(12,2) default 0,
  unidad            text default 'UNI'::text,
  stock             numeric(12,2) default 0,
  proveedor_ids     jsonb default '[]'::jsonb,
  sku_proveedor     text,
  nombre_proveedor  text,
  activo            boolean default true,
  creado            timestamptz default now(),
  tipo_empaque      text default 'unidad'::text,
  unidades_por_caja integer,
  stock_cajas       numeric(12,2) default 0,
  marca             text,
  precio_caja       numeric default 0,
  precio_unidad     numeric default 0,
  conversiones      jsonb default '[]'::jsonb,
  categoria         text
);

create table if not exists public.talonarios (
  id             bigint generated always as identity primary key,
  numero_inicial integer not null,
  numero_final   integer not null,
  cantidad       integer not null default 50,
  asignado_a     text,
  asignado_id    bigint,
  descripcion    text,
  estado         text default 'activo'::text,
  fecha_entrega  date default CURRENT_DATE,
  creado         timestamptz default now()
);


-- ── Clientes (se referencia a sí mismo por las sedes) ───────
create table if not exists public.clientes (
  id                  bigint generated always as identity primary key,
  nit                 text not null default 'CF'::text,
  nombre              text not null,
  razon_social        text,
  direccion           text,
  email               text,
  tiempo_credito      integer default 0,
  vendedor_id         bigint references public.vendedores(id) on delete set null,
  sedes_de            bigint references public.clientes(id) on delete set null,
  contacto_pagos      jsonb default '{}'::jsonb,
  contacto_compras    jsonb default '{}'::jsonb,
  precios             jsonb default '{}'::jsonb,
  activo              boolean default true,
  creado              timestamptz default now(),
  direccion_entrega   text,
  fecha_alta          date,
  nits_secundarios    jsonb default '[]'::jsonb,
  cobro_info          jsonb default '{}'::jsonb,
  seguimientos        jsonb default '[]'::jsonb,
  sub_vendedor_nombre text,
  ruta                text
);


-- ── Documentos y su cobranza ────────────────────────────────
create table if not exists public.documentos (
  id                  bigint generated always as identity primary key,
  numero              bigint,
  tipo_doc            text not null,
  cliente_id          bigint references public.clientes(id),
  cliente_nombre      text,
  cliente_comercial   text,
  cliente_nit         text,
  vendedor_id         bigint references public.vendedores(id) on delete set null,
  vendedor_nombre     text,
  items               jsonb not null default '[]'::jsonb,
  totales             jsonb not null default '{}'::jsonb,
  estado              text default 'abierto'::text,
  estado_pago         text default 'pendiente'::text,
  inventario_rebajado boolean default false,
  autorizacion        text,
  serie               text,
  numero_dte          text,
  orden_compra        text,
  dias_credito        integer default 0,
  vencimiento         timestamptz,
  exenta              boolean default false,
  escenario_exenta    text,
  piloto_id           bigint references public.pilotos(id) on delete set null,
  orden_ruta          integer,
  estado_entrega      text default 'sin'::text,
  entrega_info        jsonb,
  anulado             boolean default false,
  motivo_anulacion    text,
  creada              timestamptz default now(),
  pdf_base64          text,
  xml_base64          text,
  fecha_certificacion text,
  sub_vendedor_nombre text,
  factura_origen_id   bigint,
  nit_facturado       text,
  nombre_facturado    text,
  nota_interna        text,
  observaciones       text,
  anulado_fecha       text,
  anulado_por         text,
  sede                text,
  costo_historico     numeric
);

create table if not exists public.abonos (
  id                bigint generated always as identity primary key,
  documento_id      bigint references public.documentos(id) on delete cascade,
  fecha             date default CURRENT_DATE,
  monto             numeric(12,2) not null,
  metodo            text,
  referencia        text,
  no_recibo         text,
  comprobante       text,
  registrado_por    text,
  registrado_el     timestamptz default now(),
  anulado           boolean default false,
  motivo_anulacion  text,
  origen_cobro_ruta bigint,
  creado            timestamptz default now(),
  cuenta_banco_id   bigint references public.cuentas_banco(id)
);

create table if not exists public.cobros_ruta (
  id                bigint generated always as identity primary key,
  documento_id      bigint references public.documentos(id) on delete cascade,
  doc_num           text,
  cliente           text,
  monto             numeric(12,2) not null,
  modo              text,
  no_boleta         text,
  no_recibo         text,
  cheque            text,
  banco             text,
  piloto            text,
  fecha             timestamptz default now(),
  estado            text default 'cobrado'::text,
  depositado_fecha  timestamptz,
  recibido_por      text,
  recibido_fecha    timestamptz,
  procesado_por     text,
  procesado_fecha   timestamptz
);


-- ── Compras y pagos a proveedores ───────────────────────────
create table if not exists public.compras (
  id               bigint generated always as identity primary key,
  proveedor_id     bigint references public.proveedores(id),
  proveedor_nombre text,
  items            jsonb not null default '[]'::jsonb,
  total            numeric(12,2) default 0,
  fecha            timestamptz default now(),
  estado_recepcion text default 'pendiente'::text,
  facturada        boolean default false,
  doc_prov         text,
  tipo_pago        text default 'contado'::text,
  dias_credito     integer default 0,
  vencimiento      timestamptz,
  especial         boolean default false,
  oficializada     boolean default true,
  anulado          boolean default false,
  motivo_anulacion text,
  creada           timestamptz default now(),
  mes              text
);

create table if not exists public.pagos_proveedor (
  id               bigint generated always as identity primary key,
  compra_id        bigint references public.compras(id) on delete cascade,
  fecha            date default CURRENT_DATE,
  monto            numeric(12,2) not null,
  metodo           text,
  referencia       text,
  no_recibo        text,
  comprobante      text,
  registrado_por   text,
  registrado_el    timestamptz default now(),
  anulado          boolean default false,
  motivo_anulacion text,
  es_cierre        boolean default false,
  creado           timestamptz default now(),
  cuenta_banco_id  bigint references public.cuentas_banco(id)
);


-- ── Cotizaciones y créditos del cliente ─────────────────────
create table if not exists public.cotizaciones (
  id                   bigint generated always as identity primary key,
  numero               integer,
  cliente_id           bigint,
  cliente_nombre       text,
  cliente_comercial    text,
  cliente_nit          text,
  vendedor_id          bigint,
  vendedor_nombre      text,
  items                jsonb default '[]'::jsonb,
  totales              jsonb default '{}'::jsonb,
  observaciones        text,
  validez_dias         integer default 15,
  fecha_vence          date,
  estado               text default 'borrador'::text,
  creado_por           text,
  creada               timestamptz default now(),
  convertido_pedido_id bigint,
  vendedor_tel         text,
  vendedor_email       text,
  cliente_contacto     text,
  cliente_tel          text,
  cliente_email        text
);

create table if not exists public.creditos_cliente (
  id               bigint generated by default as identity primary key,
  cliente_id       bigint,
  tipo             text not null default 'ingreso'::text,
  monto            numeric not null default 0,
  fecha            date,
  documento_id     bigint,
  no_recibo        text,
  metodo           text,
  referencia       text,
  cuenta_banco_id  bigint,
  concepto         text,
  registrado_por   text,
  registrado_el    timestamptz default now(),
  anulado          boolean default false,
  motivo_anulacion text
);


-- ── Bancos ──────────────────────────────────────────────────
create table if not exists public.movimientos_banco (
  id                bigint generated by default as identity primary key,
  cuenta_id         bigint references public.cuentas_banco(id),
  fecha             date not null default CURRENT_DATE,
  tipo              text not null,
  monto             numeric not null,
  concepto          text,
  categoria         text,
  origen            text,
  origen_id         bigint,
  cuenta_destino_id bigint references public.cuentas_banco(id),
  referencia        text,
  registrado_por    text,
  registrado_el     timestamptz default now(),
  anulado           boolean default false,
  poliza            integer
);


-- ── Configuración, tareas, talonarios ───────────────────────
create table if not exists public.dashboard_config (
  rol    text not null primary key,
  config jsonb not null default '{}'::jsonb
);

create table if not exists public.recordatorios (
  id               bigint generated by default as identity primary key,
  titulo           text not null,
  nota             text,
  tipo             text not null default 'tarea'::text,
  ref_id           bigint,
  ref_label        text,
  fecha_vencimiento date,
  asignado_a       text,
  creado_por       text,
  prioridad        text default 'normal'::text,
  hecho            boolean default false,
  hecho_por        text,
  hecho_fecha      timestamptz,
  creado           timestamptz default now()
);

create table if not exists public.recibos_anulados (
  id           bigint generated always as identity primary key,
  numero       integer not null,
  talonario_id bigint references public.talonarios(id) on delete set null,
  motivo       text,
  anulado_por  text,
  fecha        timestamptz default now()
);


-- ── Roles y usuarios ────────────────────────────────────────
create table if not exists public.roles (
  rol               text not null primary key,
  label             text not null,
  views             jsonb not null default '[]'::jsonb,
  anular            boolean default false,
  facturar          boolean default false,
  crear_cliente     boolean default false,
  editar_inventario boolean default false,
  registrar_abono   boolean default false,
  readonly          boolean default false,
  compra_especial   boolean default false,
  asignar_piloto    boolean default false,
  convertir_cajas   boolean default false
);

create table if not exists public.usuarios (
  id             bigint generated always as identity primary key,
  auth_id        uuid references auth.users(id) on delete set null,
  nombre         text not null,
  correo         text unique,
  rol            text not null default 'ventas'::text,
  activo         boolean default true,
  vendedor_id    bigint references public.vendedores(id) on delete set null,
  piloto_id      bigint references public.pilotos(id) on delete set null,
  creado         timestamptz default now(),
  recibe_resumen boolean default false
);


-- ── Auditoría (bitácora encadenada) ─────────────────────────
create table if not exists public.auditoria (
  seq       bigint generated always as identity primary key,
  fecha     timestamptz default now(),
  usuario   text,
  rol       text,
  accion    text,
  detalle   text,
  prev_hash text,
  hash      text
);


-- ── Índices (los de rendimiento y el único de recibos) ──────
create index if not exists idx_abonos_documento        on public.abonos            (documento_id);
create index if not exists idx_clientes_nit            on public.clientes          (nit);
create index if not exists idx_clientes_vendedor       on public.clientes          (vendedor_id);
create index if not exists idx_cobros_ruta_estado      on public.cobros_ruta       (estado);
create index if not exists idx_compras_proveedor       on public.compras           (proveedor_id);
create index if not exists creditos_cliente_cliente_idx on public.creditos_cliente (cliente_id);
create index if not exists idx_documentos_cliente      on public.documentos        (cliente_id);
create index if not exists idx_documentos_estado       on public.documentos        (estado);
create index if not exists idx_documentos_piloto       on public.documentos        (piloto_id);
create index if not exists idx_documentos_tipo         on public.documentos        (tipo_doc);
create index if not exists idx_mov_cuenta              on public.movimientos_banco (cuenta_id);
create index if not exists idx_mov_fecha               on public.movimientos_banco (fecha);
create index if not exists idx_pagos_compra            on public.pagos_proveedor   (compra_id);
create unique index if not exists idx_recibos_anulados_numero on public.recibos_anulados (numero);
create index if not exists idx_talonarios_rango        on public.talonarios        (numero_inicial, numero_final);


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260805000000_base_historico.sql                       ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- BASE HISTÓRICA — todo lo que ya estaba aplicado antes de que
-- el proyecto empezara a usar migraciones versionadas.
-- ============================================================
-- Es la unión de las migraciones sueltas que se corrían a mano:
--   migracion-ola1.sql · migracion-ola2.sql · migracion-ola3.sql
--   migracion-cobros.sql · migracion-precio-caja.sql
--   migracion-completa.sql · sync-pruebas.sql
--
-- En las bases que YA existen (Producción y Pruebas) esta migración
-- no se ejecuta: baseline.sql la marca como aplicada, porque estos
-- cambios ya están ahí desde hace meses.
--
-- Existe para las bases NUEVAS — cada cliente que se sume arranca
-- corriendo esto primero y queda con el mismo esquema que SEFE.
--
-- Todo usa "if not exists", así que es seguro correrlo de más.
-- ============================================================


-- ── DOCUMENTOS ──────────────────────────────────────────────
-- Nota de crédito ligada a su factura de origen, y el NIT
-- secundario al que se facturó (puede no ser el del cliente).
alter table documentos add column if not exists factura_origen_id   bigint;
alter table documentos add column if not exists nit_facturado       text;
alter table documentos add column if not exists nombre_facturado    text;
-- Sub-vendedor (viene de Whaticket)
alter table documentos add column if not exists sub_vendedor_nombre text;


-- ── CLIENTES ────────────────────────────────────────────────
-- Pestañas "Cobros" y "Seguimiento" de la ficha del cliente
alter table clientes add column if not exists cobro_info          jsonb default '{}'::jsonb;
alter table clientes add column if not exists seguimientos        jsonb default '[]'::jsonb;
alter table clientes add column if not exists sub_vendedor_nombre text;


-- ── PRODUCTOS ───────────────────────────────────────────────
-- 'precio' es el precio de la CAJA; 'precio_unidad' el de la
-- unidad suelta (se calcula solo, pero se puede editar).
alter table productos add column if not exists precio_unidad numeric default 0;
-- Equivalencias entre presentaciones
alter table productos add column if not exists conversiones  jsonb default '[]'::jsonb;


-- ── COMPRAS ─────────────────────────────────────────────────
-- Sin esto, al recargar, una compra especial del mes en curso
-- aparecía como "vencida" y no dejaba editarla.
alter table compras add column if not exists mes text;


-- ── MOVIMIENTOS DE BANCO ────────────────────────────────────
-- Correlativo de póliza en las salidas de banco
alter table movimientos_banco add column if not exists poliza integer;


-- ── USUARIOS ────────────────────────────────────────────────
-- El rol 'cobros' quedó viejo: es idéntico a 'contabilidad'.
-- En el código 'cobros' es un alias, así que nadie se bloquea;
-- esto sólo limpia los datos.
update usuarios set rol = 'contabilidad' where rol = 'cobros';


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260812024415_realtime.sql                             ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · MIGRACIÓN: SINCRONIZACIÓN EN VIVO (Realtime)
-- ============================================================
-- Correr en el SQL Editor de Supabase.
--   Primero en Pruebas:  imvoyzxdvtoktckazzsv
--   Y sólo cuando esté probado, en Producción: krbyulpmfazntjwnpxnw
--
-- Qué hace: le dice a Postgres que publique los cambios de estas
-- tablas para que el navegador los reciba por websocket. Sin esto,
-- realtime.js se conecta bien pero NO le llega ningún evento.
--
-- Es seguro correrlo varias veces (revisa antes de agregar).
-- No modifica datos: sólo activa la publicación.
-- ============================================================


-- ------------------------------------------------------------
-- 1) Agregar las tablas a la publicación de Realtime
-- ------------------------------------------------------------
-- Se hace en un bloque para poder repetirlo sin error si la tabla
-- ya estaba publicada, y para que no truene si alguna no existe
-- todavía en esta base (ej: categorias / cotizaciones en Pruebas).
do $$
declare
  t text;
  tablas text[] := array[
    'documentos', 'abonos',
    'clientes', 'productos', 'proveedores', 'categorias',
    'compras', 'pagos_proveedor',
    'cobros_ruta',
    'cuentas_banco', 'movimientos_banco',
    'talonarios', 'recibos_anulados',
    'recordatorios', 'cotizaciones',
    'usuarios',
    'auditoria'
  ];
begin
  foreach t in array tablas loop
    -- ¿existe la tabla en este proyecto?
    if not exists (
      select 1 from pg_class c
      join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relname = t and c.relkind = 'r'
    ) then
      raise notice 'omitida (no existe en esta base): %', t;
      continue;
    end if;

    -- ¿ya estaba publicada?
    if exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = t
    ) then
      raise notice 'ya estaba publicada: %', t;
      continue;
    end if;

    execute format('alter publication supabase_realtime add table public.%I', t);
    raise notice 'publicada: %', t;
  end loop;
end $$;


-- ------------------------------------------------------------
-- 2) Verificar el resultado
-- ------------------------------------------------------------
-- Debe listar todas las tablas de arriba que existan en esta base.
select tablename as "tabla publicada en realtime"
from pg_publication_tables
where pubname = 'supabase_realtime' and schemaname = 'public'
order by tablename;


-- ============================================================
-- NOTAS
-- ============================================================
--
-- · SOBRE LOS DELETE
--   Por defecto Postgres sólo manda la llave primaria cuando se
--   borra una fila (REPLICA IDENTITY DEFAULT). realtime.js ya está
--   escrito contando con eso: cuando se borra un abono y el evento
--   no trae el documento_id, busca al documento padre que tenga ese
--   abono en su lista. Por eso NO hace falta REPLICA IDENTITY FULL,
--   que sería más pesado para la base.
--
-- · SOBRE RLS (lo siguiente que toca)
--   Realtime respeta las políticas RLS. Como todavía no hay RLS,
--   hoy cada usuario conectado recibe los cambios de todas estas
--   tablas. Eso NO empeora la exposición actual (con la anon key
--   ya se puede leer todo), pero es exactamente lo que RLS viene
--   a cerrar en el siguiente paso.
--
-- · PARA DESACTIVAR UNA TABLA
--   Si alguna resulta muy ruidosa (la candidata es 'auditoria',
--   porque cada acción del sistema escribe ahí):
--       alter publication supabase_realtime drop table public.auditoria;
--   y quitarla también del objeto TABLAS en realtime.js.
--
-- ============================================================
-- FIN
-- ============================================================


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260812030419_rls.sql                                  ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · MIGRACIÓN: SEGURIDAD A NIVEL DE BASE (RLS)
-- ============================================================
-- ⚠️ CORRER PRIMERO EN PRUEBAS (imvoyzxdvtoktckazzsv).
--    Sólo pasar a Producción (krbyulpmfazntjwnpxnw) cuando hayas
--    verificado que TODOS los roles pueden entrar y trabajar.
--    Si algo sale mal: correr migracion-rls-revertir.sql.
--
-- ⚠️ ANTES DE CORRER ESTO hay que subir el arreglo del login
--    (el commit que acompaña este archivo). Sin él, nadie puede
--    entrar: la app busca tu usuario en una lista que se carga
--    ANTES de autenticarte, y con RLS esa lista viene vacía.
--
-- ------------------------------------------------------------
-- QUÉ PROBLEMA RESUELVE
-- ------------------------------------------------------------
-- Hoy los permisos de SEFE viven sólo en el navegador: el objeto
-- ROLES esconde botones y secciones. Eso ordena la pantalla, pero
-- no protege nada. La anon key está en el repo (como debe ser en
-- Supabase), así que hoy CUALQUIERA que la tenga puede leer y
-- escribir todas las tablas desde la consola del navegador, sin
-- siquiera iniciar sesión.
--
-- Después de esta migración:
--   · Sin sesión válida no se lee ni se escribe NADA.
--   · Un usuario inactivo queda fuera aunque su clave sirva.
--   · Un rol de sólo lectura (Auditoría) no puede escribir nada.
--   · Nadie puede subirse el rol a admin desde la consola.
--   · El registro de auditoría no se puede alterar ni borrar.
--
-- ------------------------------------------------------------
-- QUÉ *NO* RESUELVE TODAVÍA (a propósito)
-- ------------------------------------------------------------
-- Esta es la CAPA 1: separa "cualquiera en internet" de "tu gente".
-- Dentro de tu gente, cualquier usuario activo puede leer todas
-- las tablas y escribir en las operativas.
--
-- El ajuste fino por rol (que Ventas no lea los costos de compra,
-- por ejemplo) es la CAPA 2, y se hace después. Va aparte por una
-- razón concreta: si una política queda más estricta que la
-- pantalla, se rompen flujos que hoy funcionan y es muy difícil
-- darse cuenta (las filas simplemente no aparecen, sin error).
--
-- Ejemplo real de por qué hay que ir despacio: el rol Facturador
-- tiene editarInventario=false, pero al facturar el sistema
-- descuenta el stock. Si RLS exigiera editarInventario para tocar
-- 'productos', facturar dejaría de rebajar inventario en silencio.
--
-- Es seguro correr este archivo varias veces.
-- ============================================================


-- ============================================================
-- PARTE 1 · FUNCIONES DE APOYO
-- ============================================================
-- Van con SECURITY DEFINER a propósito: necesitan leer 'usuarios'
-- y 'roles' saltándose RLS. Si no, se armaría una recursión
-- infinita (para saber si podés leer usuarios hay que leer
-- usuarios). El search_path fijo es obligatorio en estas
-- funciones para que nadie pueda secuestrarlas.

-- ── ¿Qué rol tiene el que está conectado? ───────────────────
-- Devuelve NULL si no hay sesión, si el correo no está en la
-- tabla usuarios, o si el usuario está marcado como inactivo.
-- NULL = sin acceso a nada.
--
-- Busca igual que el backend (server.js): primero por auth_id, y
-- si no, por correo. El ::text es para que funcione sin importar
-- si auth_id quedó como uuid o como text.
create or replace function public.sefe_rol()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select u.rol
  from usuarios u
  where (
          u.auth_id::text = auth.uid()::text
          or lower(u.correo) = lower(coalesce(auth.jwt() ->> 'email', ''))
        )
    and coalesce(u.activo, true) = true
  order by (u.auth_id::text = auth.uid()::text) desc nulls last
  limit 1
$$;

-- ── ¿Hay alguien válido conectado? ──────────────────────────
create or replace function public.sefe_activo()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.sefe_rol() is not null
$$;

-- ── ¿Es administrador? ──────────────────────────────────────
create or replace function public.sefe_es_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.sefe_rol() = 'admin'
$$;

-- ── ¿Su rol es de sólo lectura? ─────────────────────────────
-- Lee el flag de la tabla 'roles', que es la que edita el admin
-- desde la pantalla de Usuarios. Así, cambiar un permiso en la
-- pantalla cambia también lo que permite la base: una sola fuente
-- de verdad, sin tener que volver a tocar SQL.
create or replace function public.sefe_solo_lectura()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select coalesce(r.readonly, false) from roles r where r.rol = public.sefe_rol()),
    false
  )
$$;

-- ── ¿Puede escribir? ────────────────────────────────────────
-- Es el permiso base de escritura: sesión válida, usuario activo
-- y rol que no sea de sólo lectura.
create or replace function public.sefe_puede_escribir()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.sefe_rol() is not null and not public.sefe_solo_lectura()
$$;

-- Que sólo las pueda ejecutar quien tenga sesión.
revoke all on function public.sefe_rol()            from public, anon;
revoke all on function public.sefe_activo()         from public, anon;
revoke all on function public.sefe_es_admin()       from public, anon;
revoke all on function public.sefe_solo_lectura()   from public, anon;
revoke all on function public.sefe_puede_escribir() from public, anon;
grant execute on function public.sefe_rol()            to authenticated;
grant execute on function public.sefe_activo()         to authenticated;
grant execute on function public.sefe_es_admin()       to authenticated;
grant execute on function public.sefe_solo_lectura()   to authenticated;
grant execute on function public.sefe_puede_escribir() to authenticated;


-- ============================================================
-- PARTE 2 · POLÍTICAS
-- ============================================================
-- Nota de rendimiento: adentro de las políticas las funciones van
-- envueltas en (select ...). No es un capricho — así Postgres las
-- evalúa UNA vez por consulta en lugar de una vez por fila. Sin
-- eso, listar 5.000 documentos ejecutaría la función 5.000 veces.
--
-- Todas las políticas son 'to authenticated'. El rol 'anon' (el de
-- la anon key sin login) no tiene ninguna política, y en RLS lo que
-- no está permitido está prohibido. O sea: sin sesión, nada.

do $$
declare
  t text;

  -- GRUPO A · Tablas operativas del día a día.
  --   leer     → cualquier usuario activo
  --   escribir → cualquier usuario activo que no sea sólo lectura
  --   borrar   → sólo admin (en SEFE casi nada se borra: se anula,
  --              que es un UPDATE y deja rastro)
  operativas text[] := array[
    'clientes', 'productos', 'proveedores', 'categorias',
    'documentos', 'abonos',
    'compras', 'pagos_proveedor',
    'cobros_ruta',
    'cuentas_banco', 'movimientos_banco',
    'talonarios', 'recibos_anulados',
    'vendedores', 'pilotos'
  ];

  -- GRUPO B · Cosas que la gente crea y borra sola (tareas, cotizaciones).
  propias text[] := array['recordatorios', 'cotizaciones'];

  -- GRUPO C · Configuración sensible. Todos la leen (la app la
  -- necesita para armar la pantalla), pero SÓLO admin la escribe.
  -- Acá está la protección más importante de todo el archivo: sin
  -- esto, cualquiera puede abrir la consola y ponerse rol 'admin'.
  configuracion text[] := array['usuarios', 'roles', 'dashboard_config'];

  existe boolean;
begin
  ------------------------------------------------------------
  -- GRUPO A
  ------------------------------------------------------------
  foreach t in array operativas loop
    select exists (select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace
                   where n.nspname='public' and c.relname=t and c.relkind='r') into existe;
    if not existe then raise notice 'omitida (no existe): %', t; continue; end if;

    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists sefe_leer on public.%I', t);
    execute format($f$create policy sefe_leer on public.%I
                      for select to authenticated
                      using ((select public.sefe_activo()))$f$, t);

    execute format('drop policy if exists sefe_crear on public.%I', t);
    execute format($f$create policy sefe_crear on public.%I
                      for insert to authenticated
                      with check ((select public.sefe_puede_escribir()))$f$, t);

    execute format('drop policy if exists sefe_editar on public.%I', t);
    execute format($f$create policy sefe_editar on public.%I
                      for update to authenticated
                      using ((select public.sefe_puede_escribir()))
                      with check ((select public.sefe_puede_escribir()))$f$, t);

    execute format('drop policy if exists sefe_borrar on public.%I', t);
    execute format($f$create policy sefe_borrar on public.%I
                      for delete to authenticated
                      using ((select public.sefe_es_admin()))$f$, t);

    raise notice 'protegida (operativa): %', t;
  end loop;

  ------------------------------------------------------------
  -- GRUPO B
  ------------------------------------------------------------
  foreach t in array propias loop
    select exists (select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace
                   where n.nspname='public' and c.relname=t and c.relkind='r') into existe;
    if not existe then raise notice 'omitida (no existe): %', t; continue; end if;

    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists sefe_leer on public.%I', t);
    execute format($f$create policy sefe_leer on public.%I
                      for select to authenticated
                      using ((select public.sefe_activo()))$f$, t);

    execute format('drop policy if exists sefe_crear on public.%I', t);
    execute format($f$create policy sefe_crear on public.%I
                      for insert to authenticated
                      with check ((select public.sefe_puede_escribir()))$f$, t);

    execute format('drop policy if exists sefe_editar on public.%I', t);
    execute format($f$create policy sefe_editar on public.%I
                      for update to authenticated
                      using ((select public.sefe_puede_escribir()))
                      with check ((select public.sefe_puede_escribir()))$f$, t);

    execute format('drop policy if exists sefe_borrar on public.%I', t);
    execute format($f$create policy sefe_borrar on public.%I
                      for delete to authenticated
                      using ((select public.sefe_puede_escribir()))$f$, t);

    raise notice 'protegida (propia): %', t;
  end loop;

  ------------------------------------------------------------
  -- GRUPO C
  ------------------------------------------------------------
  foreach t in array configuracion loop
    select exists (select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace
                   where n.nspname='public' and c.relname=t and c.relkind='r') into existe;
    if not existe then raise notice 'omitida (no existe): %', t; continue; end if;

    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists sefe_leer on public.%I', t);
    execute format($f$create policy sefe_leer on public.%I
                      for select to authenticated
                      using ((select public.sefe_activo()))$f$, t);

    execute format('drop policy if exists sefe_crear on public.%I', t);
    execute format($f$create policy sefe_crear on public.%I
                      for insert to authenticated
                      with check ((select public.sefe_es_admin()))$f$, t);

    execute format('drop policy if exists sefe_editar on public.%I', t);
    execute format($f$create policy sefe_editar on public.%I
                      for update to authenticated
                      using ((select public.sefe_es_admin()))
                      with check ((select public.sefe_es_admin()))$f$, t);

    execute format('drop policy if exists sefe_borrar on public.%I', t);
    execute format($f$create policy sefe_borrar on public.%I
                      for delete to authenticated
                      using ((select public.sefe_es_admin()))$f$, t);

    raise notice 'protegida (configuración, sólo admin escribe): %', t;
  end loop;
end $$;


-- ------------------------------------------------------------
-- AUDITORÍA · caso aparte: sólo se agrega, nunca se toca
-- ------------------------------------------------------------
-- El log encadena hashes (prev_hash → hash) justamente para que
-- no se pueda alterar sin que se note. Sería incoherente dejar
-- que alguien lo edite o lo borre. Acá NO hay política de UPDATE
-- ni de DELETE: eso significa que nadie puede hacerlo — tampoco
-- el admin. Para tocarlo hay que entrar al panel de Supabase, que
-- es exactamente la fricción que se busca.
--
-- El INSERT no depende de sefe_puede_escribir(): un usuario de
-- sólo lectura casi no genera acciones, pero si el sistema decide
-- registrar algo, nunca debe quedar sin registrar.
do $$
begin
  if exists (select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace
             where n.nspname='public' and c.relname='auditoria' and c.relkind='r') then
    alter table public.auditoria enable row level security;

    drop policy if exists sefe_leer   on public.auditoria;
    drop policy if exists sefe_crear  on public.auditoria;
    drop policy if exists sefe_editar on public.auditoria;
    drop policy if exists sefe_borrar on public.auditoria;

    create policy sefe_leer on public.auditoria
      for select to authenticated
      using ((select public.sefe_activo()));

    create policy sefe_crear on public.auditoria
      for insert to authenticated
      with check ((select public.sefe_activo()));

    raise notice 'protegida (sólo se agrega, nadie edita ni borra): auditoria';
  end if;
end $$;


-- ============================================================
-- PARTE 3 · VERIFICACIÓN
-- ============================================================

-- 1) Todas las tablas deben decir RLS = true.
--    Si alguna dice false, quedó desprotegida.
select c.relname as tabla,
       c.relrowsecurity as "RLS activo",
       count(p.polname) as politicas
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
left join pg_policy p on p.polrelid = c.oid
where n.nspname = 'public' and c.relkind = 'r'
group by c.relname, c.relrowsecurity
order by c.relrowsecurity, c.relname;

-- 2) Comprobar que TU usuario quedó bien reconocido.
--    Corriendo esto desde el SQL Editor da NULL (ahí no hay sesión
--    de usuario, es normal). La prueba de verdad es desde la app:
--    abrí la consola del navegador ya logueado y corré:
--        await sb.rpc('sefe_rol')
--    Tiene que devolver tu rol ('admin', 'ventas', …).

-- 3) Que no haya usuarios huérfanos.
--    Un usuario cuyo correo no coincida con ninguno de Supabase Auth
--    va a poder poner su contraseña pero NO va a poder trabajar.
select u.id, u.nombre, u.correo, u.rol, u.activo,
       case when a.id is null then '⚠️ SIN CUENTA DE ACCESO' else 'ok' end as estado
from usuarios u
left join auth.users a
  on a.id::text = u.auth_id::text
  or lower(a.email) = lower(u.correo)
order by estado, u.nombre;


-- ============================================================
-- NOTAS IMPORTANTES
-- ============================================================
--
-- · EL BACKEND NO SE VE AFECTADO
--   sefe-backend usa la service_role key, que se salta RLS por
--   diseño. El resumen diario por correo y el cambio de contraseña
--   siguen funcionando igual.
--
-- · EL TIEMPO REAL SÍ RESPETA RLS
--   A partir de ahora el websocket sólo manda cambios de filas que
--   el usuario puede leer. Como en la capa 1 todo usuario activo
--   lee todo, no cambia nada en la práctica — pero cuando llegue la
--   capa 2, los filtros se aplican solos también al tiempo real,
--   sin tocar realtime.js.
--
-- · SI ALGUIEN NO PUEDE ENTRAR
--   Casi siempre es una de estas tres:
--     1. Su correo en 'usuarios' no coincide con el de Supabase Auth
--        (la consulta 3 de arriba los encuentra).
--     2. Está marcado activo = false.
--     3. Su 'rol' no existe en la tabla 'roles'.
--   Para salir del apuro rápido: correr migracion-rls-revertir.sql,
--   arreglar el dato, y volver a aplicar esta migración.
--
-- · PRÓXIMO PASO (CAPA 2)
--   Restricción de lectura por rol usando roles.views. Antes de
--   hacerla hay que recorrer los flujos que escriben en tablas que
--   el rol "no debería" tocar — como el Facturador rebajando stock.
--   Esos casos son los que rompen en silencio.
--
-- ============================================================
-- FIN
-- ============================================================


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260819120000_sede_documento.sql                       ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- Sede en los documentos (para las Notas de préstamo)
-- ============================================================
-- Grupo Gecko (y otros) se manejan centralizados, sin sedes creadas
-- como clientes aparte. Para llevar control de las Notas de préstamo se
-- guarda una "sede" de texto libre en el documento, que sale al lado del
-- nombre del cliente en la NP.
--
-- Seguro de correr de más: 'if not exists' no duplica ni toca datos.
-- ============================================================

alter table documentos add column if not exists sede text;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260820130000_creditos_cliente.sql                     ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Saldo a favor del cliente (creditos_cliente)
-- ============================================================
-- Cuando un cliente deposita de más (o paga por adelantado), el
-- excedente queda como CRÉDITO a su favor y se puede aplicar a una
-- factura futura. Esta tabla es el libro de ese saldo a favor:
--
--   tipo = 'ingreso'     → entra saldo a favor (sobrepago / anticipo)
--   tipo = 'aplicacion'  → se usa saldo a favor en una factura
--
-- Saldo a favor del cliente = Σ(ingreso) − Σ(aplicacion), sin anulados.
--
-- Seguro de correr de más: todo es 'if not exists' / 'drop ... if exists'.
-- El RLS reutiliza las funciones sefe_* de la migración de seguridad.
-- ============================================================

create table if not exists public.creditos_cliente (
  id            bigint generated by default as identity primary key,
  cliente_id    bigint,
  tipo          text not null default 'ingreso',   -- 'ingreso' | 'aplicacion'
  monto         numeric not null default 0,
  fecha         date,
  documento_id  bigint,                             -- factura de origen (ingreso) o donde se aplicó (aplicacion)
  no_recibo     text,
  metodo        text,
  referencia    text,
  cuenta_banco_id bigint,
  concepto      text,
  registrado_por text,
  registrado_el timestamptz default now(),
  anulado       boolean default false,
  motivo_anulacion text
);

create index if not exists creditos_cliente_cliente_idx on public.creditos_cliente (cliente_id);

-- ── RLS: misma regla que las tablas operativas ──────────────
--   leer     → cualquier usuario activo
--   escribir → usuario activo que no sea sólo lectura
--   borrar   → sólo admin (casi nada se borra: se anula, que es UPDATE)
alter table public.creditos_cliente enable row level security;

drop policy if exists sefe_leer on public.creditos_cliente;
create policy sefe_leer on public.creditos_cliente
  for select to authenticated
  using ((select public.sefe_activo()));

drop policy if exists sefe_crear on public.creditos_cliente;
create policy sefe_crear on public.creditos_cliente
  for insert to authenticated
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_editar on public.creditos_cliente;
create policy sefe_editar on public.creditos_cliente
  for update to authenticated
  using ((select public.sefe_puede_escribir()))
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_borrar on public.creditos_cliente;
create policy sefe_borrar on public.creditos_cliente
  for delete to authenticated
  using ((select public.sefe_es_admin()));


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260820160000_costo_historico_documento.sql            ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Costo histórico por factura (costo_historico)
-- ============================================================
-- Las ventas de ene–jul 2026 se importaron sólo con el TOTAL, sin el
-- detalle de productos. Sin líneas, el sistema no puede calcular el costo
-- de lo vendido de ese período (da Q0 y margen 100%).
--
-- Como no existe el detalle por producto, se guarda un COSTO por factura,
-- repartido desde el Excel oficial "ventas vs costos" (que trae el costo
-- por vendedor y mes) proporcional a la venta de cada factura. El reporte
-- usa este campo SÓLO cuando la factura no tiene líneas; para las facturas
-- normales (con detalle) sigue calculando el costo real por producto.
--
-- Seguro de correr de más: 'if not exists' no duplica ni toca datos.
-- El relleno de valores va aparte (herramienta puntual), no en esta
-- migración de esquema.
-- ============================================================

alter table documentos add column if not exists costo_historico numeric;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260825120000_indices_reportes.sql                     ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- ÍNDICES para acelerar los reportes
-- ============================================================
-- Los reportes filtran y agrupan mucho por fecha y por vendedor,
-- pero esas columnas no tenían índice, así que con datos de años
-- Postgres barría toda la tabla. Estos índices lo evitan.
--
-- Sólo agrega índices: NO toca datos ni estructura. Con
-- "if not exists" es seguro correrlo de más (no-op si ya están).
-- ============================================================

-- Comparativas por mes / rangos de fecha
create index if not exists idx_documentos_creada
  on public.documentos (creada);

-- Reportes por vendedor
create index if not exists idx_documentos_vendedor
  on public.documentos (vendedor_id);

-- Cobranza por período (fecha de los abonos)
create index if not exists idx_abonos_fecha
  on public.abonos (fecha);


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260825140000_correlativos_secuencias.sql              ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- Correlativos con secuencias de Postgres
-- ============================================================
-- Los números de negocio (documentos.numero y cotizaciones.numero)
-- se calculaban con max+1 EN EL NAVEGADOR: dos personas creando a la
-- vez podían sacar el mismo número.
--
-- Acá se crea una secuencia por cada uno y se pone como DEFAULT de la
-- columna. Cuando el código deje de mandar el número al insertar
-- (cambio que va APARTE, en un segundo paso), la base lo asigna sola,
-- sin posibilidad de colisión.
--
-- IMPORTANTE — esto es SEGURO de publicar solo: mientras el código
-- siga mandando el número, este DEFAULT queda DORMIDO (el valor que
-- manda el cliente le gana al default). No cambia nada todavía.
--
-- La secuencia arranca en el máximo actual, para seguir la numeración
-- sin repetir. Puede dejar huecos si un pedido se cancela — es lo
-- correcto para un correlativo interno: mejor un hueco que un choque.
-- (El número fiscal de la factura FEL no se toca; lo da la SAT.)
--
-- Seguro de correr varias veces.
-- ============================================================

-- ── documentos.numero ───────────────────────────────────────
do $$
declare mx bigint;
begin
  select coalesce(max(numero),0) into mx from public.documentos;
  if not exists (select 1 from pg_class where relname = 'documentos_numero_seq') then
    create sequence public.documentos_numero_seq;
  end if;
  -- arranca en el máximo actual (si hay filas) o en 1 (base nueva)
  perform setval('public.documentos_numero_seq', greatest(mx, 1), mx > 0);
  alter table public.documentos
    alter column numero set default nextval('public.documentos_numero_seq');
end $$;

-- ── cotizaciones.numero ─────────────────────────────────────
do $$
declare mx bigint;
begin
  select coalesce(max(numero),0) into mx from public.cotizaciones;
  if not exists (select 1 from pg_class where relname = 'cotizaciones_numero_seq') then
    create sequence public.cotizaciones_numero_seq;
  end if;
  perform setval('public.cotizaciones_numero_seq', greatest(mx, 1), mx > 0);
  alter table public.cotizaciones
    alter column numero set default nextval('public.cotizaciones_numero_seq');
end $$;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260829120000_conciliado_banco.sql                     ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Marca de conciliación en los movimientos de banco
-- ============================================================
-- Agrega a 'movimientos_banco' la marca de que un movimiento ya se
-- cuadró contra el estado de cuenta del banco (pantalla de Conciliación
-- bancaria). 'conciliado' = verificado con el banco; 'conciliado_el' =
-- cuándo se marcó.
--
-- Seguro de correr de más: 'if not exists' no duplica ni toca datos, y
-- el default 'false' deja todo lo viejo como "sin conciliar" (que es lo
-- correcto).
-- ============================================================

alter table movimientos_banco
  add column if not exists conciliado boolean not null default false;

alter table movimientos_banco
  add column if not exists conciliado_el timestamptz;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260829140000_conciliaciones.sql                       ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Historial de conciliaciones bancarias
-- ============================================================
-- Guarda el "cierre" de cada conciliación: cuenta, período, saldos,
-- diferencia y cuántos movimientos quedaron conciliados / pendientes.
-- Sirve de respaldo (para el contador / auditoría) y para no repetir
-- trabajo mes a mes.
--
-- Seguro de correr de más: 'if not exists' no duplica ni toca datos.
-- ============================================================

create table if not exists conciliaciones (
  id            bigserial primary key,
  cuenta_id     bigint,
  periodo_desde date,
  periodo_hasta date,
  saldo_banco   numeric,
  saldo_sefe    numeric,
  diferencia    numeric,
  n_conciliados integer,
  n_solo_banco  integer,
  n_solo_sefe   integer,
  archivo       text,
  notas         text,
  guardado_por  text,
  guardado_el   timestamptz default now()
);


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260829160000_empleados.sql                            ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Empleados (base del módulo de Planilla)
-- ============================================================
-- Maestro de empleados para la planilla quincenal. El sueldo base es
-- quincenal. 'vendedor_id' liga al vendedor para traer las comisiones
-- automáticamente desde las ventas.
--
-- Seguro de correr de más: 'if not exists' no duplica ni toca datos.
-- ============================================================

create table if not exists empleados (
  id                bigserial primary key,
  nombre            text not null,
  puesto            text,
  dpi               text,
  nit               text,
  igss_afiliacion   text,
  vendedor_id       bigint,
  sueldo_base       numeric not null default 0,   -- quincenal
  bonif_incentivo   numeric not null default 0,
  cuenta_banco_id   bigint,
  activo            boolean not null default true,
  fecha_ingreso     date,
  creado            timestamptz default now()
);


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260829170000_rls_tablas_nuevas.sql                    ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · RLS para las tablas nuevas (empleados, conciliaciones)
-- ============================================================
-- Las tablas 'empleados' y 'conciliaciones' se crearon sin políticas
-- de seguridad, y como el proyecto tiene RLS activo (ver
-- 20260812030419_rls.sql), la base bloqueaba leer/escribir desde el
-- navegador. Esto les pone las MISMAS políticas que las tablas
-- operativas, reusando las funciones sefe_* que ya existen.
--
-- Seguro de correr de más: usa 'if exists' / 'drop policy if exists'.
-- ============================================================

do $$
declare t text;
begin
  foreach t in array array['empleados','conciliaciones'] loop
    if exists (select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace
               where n.nspname='public' and c.relname=t and c.relkind='r') then

      execute format('alter table public.%I enable row level security', t);

      execute format('drop policy if exists sefe_leer on public.%I', t);
      execute format($f$create policy sefe_leer on public.%I
                        for select to authenticated
                        using ((select public.sefe_activo()))$f$, t);

      execute format('drop policy if exists sefe_crear on public.%I', t);
      execute format($f$create policy sefe_crear on public.%I
                        for insert to authenticated
                        with check ((select public.sefe_puede_escribir()))$f$, t);

      execute format('drop policy if exists sefe_editar on public.%I', t);
      execute format($f$create policy sefe_editar on public.%I
                        for update to authenticated
                        using ((select public.sefe_puede_escribir()))
                        with check ((select public.sefe_puede_escribir()))$f$, t);

      execute format('drop policy if exists sefe_borrar on public.%I', t);
      execute format($f$create policy sefe_borrar on public.%I
                        for delete to authenticated
                        using ((select public.sefe_es_admin()))$f$, t);

      execute format('grant select, insert, update, delete on public.%I to authenticated', t);
    end if;
  end loop;
  -- Que las secuencias (id bigserial) sean usables al insertar.
  grant usage, select on all sequences in schema public to authenticated;
end $$;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260829180000_planillas.sql                            ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Planillas quincenales (módulo de Planilla, parte 2)
-- ============================================================
-- Guarda cada corrida de planilla. El detalle (una fila por
-- empleado: sueldo, bonificación, comisiones, IGSS, ISR, neto,
-- estado de pago, póliza) va en la columna JSONB 'lineas'. Las
-- columnas sueltas son el resumen para listar y reportar.
--
-- Incluye SUS POLÍTICAS RLS desde el inicio (el proyecto tiene RLS
-- activo — una tabla sin políticas queda cerrada al navegador).
-- Seguro de correr de más: usa 'if not exists' / 'drop policy if exists'.
-- ============================================================

create table if not exists public.planillas (
  id             bigserial primary key,
  periodo_desde  date,
  periodo_hasta  date,
  etiqueta       text,
  estado         text not null default 'borrador',   -- borrador | parcial | pagada
  total_ingresos numeric not null default 0,
  total_descuentos numeric not null default 0,
  total_neto     numeric not null default 0,
  n_empleados    integer not null default 0,
  notas          text,
  lineas         jsonb not null default '[]'::jsonb,
  creado_por     text,
  creado_el      timestamptz not null default now(),
  actualizado_el timestamptz
);

-- ── RLS: mismas políticas que las demás tablas operativas ──
alter table public.planillas enable row level security;

drop policy if exists sefe_leer   on public.planillas;
create policy sefe_leer   on public.planillas for select to authenticated
  using ((select public.sefe_activo()));

drop policy if exists sefe_crear  on public.planillas;
create policy sefe_crear  on public.planillas for insert to authenticated
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_editar on public.planillas;
create policy sefe_editar on public.planillas for update to authenticated
  using ((select public.sefe_puede_escribir()))
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_borrar on public.planillas;
create policy sefe_borrar on public.planillas for delete to authenticated
  using ((select public.sefe_es_admin()));

grant select, insert, update, delete on public.planillas to authenticated;
grant usage, select on sequence public.planillas_id_seq to authenticated;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260830100000_ctrl_ambientales.sql                     ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · Controles — Ambientales (parte 1)
-- ============================================================
-- Servicios de recarga de ambientales (aromatizadores) por cliente:
-- cliente, ubicación, aroma, fecha del servicio y próximo servicio.
--
-- Incluye SUS políticas RLS desde el inicio (el proyecto tiene RLS
-- activo: una tabla sin políticas queda cerrada al navegador).
-- Seguro de correr de más: usa 'if not exists' / 'drop policy if exists'.
-- ============================================================

create table if not exists public.ctrl_ambientales (
  id          bigserial primary key,
  cliente_id  bigint,
  ubicacion   text,
  aroma       text,
  fecha       date,
  proximo     date,
  nota        text,
  creado      timestamptz not null default now(),
  creado_por  text
);

alter table public.ctrl_ambientales enable row level security;

drop policy if exists sefe_leer   on public.ctrl_ambientales;
create policy sefe_leer   on public.ctrl_ambientales for select to authenticated
  using ((select public.sefe_activo()));

drop policy if exists sefe_crear  on public.ctrl_ambientales;
create policy sefe_crear  on public.ctrl_ambientales for insert to authenticated
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_editar on public.ctrl_ambientales;
create policy sefe_editar on public.ctrl_ambientales for update to authenticated
  using ((select public.sefe_puede_escribir()))
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_borrar on public.ctrl_ambientales;
create policy sefe_borrar on public.ctrl_ambientales for delete to authenticated
  using ((select public.sefe_es_admin()));

grant select, insert, update, delete on public.ctrl_ambientales to authenticated;
grant usage, select on sequence public.ctrl_ambientales_id_seq to authenticated;


-- ╔══════════════════════════════════════════════════════════╗
-- ║  20260831120000_rls_capa2.sql                            ║
-- ╚══════════════════════════════════════════════════════════╝

-- ============================================================
-- SEFE · MIGRACIÓN: RLS CAPA 2 — LECTURA POR ROL (back office)
-- ============================================================
-- Complementa la capa 1 (20260812030419_rls.sql). La capa 1 separó
-- "cualquiera en internet" de "tu gente". Esta capa 2 separa, DENTRO
-- de tu gente, quién ve las tablas sensibles de COMPRAS y BANCOS.
--
-- Después de esta migración:
--   · Ventas, Facturador y Piloto NO pueden leer ni escribir
--     compras, pagos a proveedor, proveedores, cuentas de banco,
--     movimientos de banco ni conciliaciones — tampoco desde la
--     consola del navegador.
--   · Admin, Gerencia, Contabilidad, Bodega y Auditoría siguen igual
--     (ellos sí trabajan con compras/bancos).
--
-- QUÉ *NO* TOCA (a propósito, para no romper en silencio):
--   · La escritura que usa la facturación: 'productos' (stock) queda
--     ABIERTO para todos, así facturar sigue rebajando inventario
--     incluso para el Facturador. Ése es el caso-trampa que marcó la
--     capa 1.
--   · El "esqueleto compartido" (clientes, productos, documentos,
--     abonos, cotizaciones, cobros_ruta, talonarios, etc.) sigue como
--     en la capa 1: cualquier usuario activo lo lee.
--   · NO oculta la COLUMNA costo dentro de 'productos'. Eso es
--     seguridad por columna (otra técnica) y queda para más adelante.
--
-- Nota de mantenimiento: esta migración corre DESPUÉS de la capa 1.
-- Si algún día se vuelve a correr SÓLO la capa 1 a mano, hay que
-- volver a correr también ésta (la capa 1 reabre estas 6 tablas).
--
-- Es seguro correr este archivo varias veces.
-- Reverso: supabase/herramientas/rls-capa2-revertir.sql
-- ============================================================


-- ── ¿El rol conectado es de "back office"? ──────────────────
-- Ve compras y bancos si es admin, si es de sólo lectura (Auditoría),
-- o si su rol tiene en 'views' alguna sección de compras/finanzas.
-- Misma fuente de verdad que la pantalla (se maneja desde Usuarios),
-- así no hay que volver a tocar SQL para cambiar un permiso.
-- SECURITY DEFINER + search_path fijo, igual que las funciones de la
-- capa 1: necesita leer 'roles' saltándose RLS y no debe ser
-- secuestrable.
create or replace function public.sefe_ve_backoffice()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.sefe_es_admin()
      or public.sefe_solo_lectura()
      or coalesce(
           (select r.views ?| array['compras','nuevacompra','porpagar','proveedores','bancos','cobros']
              from roles r where r.rol = public.sefe_rol()),
           false)
$$;

revoke all on function public.sefe_ve_backoffice() from public, anon;
grant execute on function public.sefe_ve_backoffice() to authenticated;


-- ── Políticas: compras + bancos sólo para back office ───────
-- Mismas 4 acciones que la capa 1, pero LEER/CREAR/EDITAR piden
-- además sefe_ve_backoffice(). BORRAR sigue siendo sólo admin.
-- Las funciones van envueltas en (select ...) para que Postgres las
-- evalúe una vez por consulta y no una vez por fila.
do $$
declare
  t text;
  sensibles text[] := array[
    'compras', 'pagos_proveedor', 'proveedores',
    'cuentas_banco', 'movimientos_banco', 'conciliaciones'
  ];
  existe boolean;
begin
  foreach t in array sensibles loop
    select exists (select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace
                   where n.nspname='public' and c.relname=t and c.relkind='r') into existe;
    if not existe then raise notice 'omitida (no existe): %', t; continue; end if;

    execute format('alter table public.%I enable row level security', t);

    execute format('drop policy if exists sefe_leer on public.%I', t);
    execute format($f$create policy sefe_leer on public.%I
                      for select to authenticated
                      using ((select public.sefe_activo()) and (select public.sefe_ve_backoffice()))$f$, t);

    execute format('drop policy if exists sefe_crear on public.%I', t);
    execute format($f$create policy sefe_crear on public.%I
                      for insert to authenticated
                      with check ((select public.sefe_puede_escribir()) and (select public.sefe_ve_backoffice()))$f$, t);

    execute format('drop policy if exists sefe_editar on public.%I', t);
    execute format($f$create policy sefe_editar on public.%I
                      for update to authenticated
                      using ((select public.sefe_puede_escribir()) and (select public.sefe_ve_backoffice()))
                      with check ((select public.sefe_puede_escribir()) and (select public.sefe_ve_backoffice()))$f$, t);

    execute format('drop policy if exists sefe_borrar on public.%I', t);
    execute format($f$create policy sefe_borrar on public.%I
                      for delete to authenticated
                      using ((select public.sefe_es_admin()))$f$, t);

    raise notice 'capa 2 (back office): %', t;
  end loop;
end $$;


-- ============================================================
-- VERIFICACIÓN
-- ============================================================
-- Las 6 tablas deben decir RLS=true y tener 4 políticas cada una.
select c.relname as tabla,
       c.relrowsecurity as "RLS",
       count(p.polname) as politicas
from pg_class c
join pg_namespace n on n.oid = c.relnamespace
left join pg_policy p on p.polrelid = c.oid
where n.nspname='public'
  and c.relname in ('compras','pagos_proveedor','proveedores',
                    'cuentas_banco','movimientos_banco','conciliaciones')
group by c.relname, c.relrowsecurity
order by c.relname;

-- Prueba real (desde la consola del navegador, ya logueado):
--   await sb.rpc('sefe_ve_backoffice')
--   → true  para admin/gerencia/contabilidad/bodega/auditoría
--   → false para ventas/facturador/piloto
-- ============================================================
-- FIN
-- ============================================================

