-- ============================================================
-- BASELINE — el esquema completo de SEFE, creado desde cero.
-- ============================================================
-- Esta es la PRIMERA migración: crea todas las tablas, llaves,
-- relaciones e índices de una base vacía. Va antes que
-- base_historico y que todas las demás.
--
-- ── PARA QUÉ SIRVE ──────────────────────────────────────────
-- Para dar de alta un CLIENTE NUEVO: se crea un proyecto Supabase
-- vacío y, al correr las migraciones, esto arma toda la estructura.
-- Después, base_historico y las demás migraciones agregan lo que
-- vino evolucionando — pero como todas usan "if not exists", en una
-- base recién creada por este baseline simplemente no repiten nada.
--
-- ── EN PRODUCCIÓN Y PRUEBAS (bases que YA existen) ──────────
-- Es un NO-OP total. Todo está con "create table if not exists" /
-- "create index if not exists", así que no toca ni una tabla ni un
-- dato: sólo queda registrada como aplicada. La estructura de esas
-- bases ya está desde hace meses.
--
-- ── NOTAS ───────────────────────────────────────────────────
-- · Los id son IDENTITY (los genera Postgres), tal como en la base
--   real: 'always' donde el cliente nunca los manda, 'by default'
--   donde a veces sí.
-- · Las tablas de respaldo (_bkp_*) NO van: son de una limpieza
--   puntual, no parte del sistema.
-- · Las políticas RLS y el tiempo real los agregan sus propias
--   migraciones (rls / realtime), que corren después de ésta.
-- ============================================================


-- ── Catálogos base (sin dependencias) ───────────────────────
create table if not exists public.vendedores (
  id      bigint generated always as identity primary key,
  nombre  text not null,
  activo  boolean default true,
  creado  timestamptz default now()
);

create table if not exists public.pilotos (
  id      bigint generated always as identity primary key,
  nombre  text not null,
  activo  boolean default true,
  creado  timestamptz default now()
);

create table if not exists public.proveedores (
  id           bigint generated always as identity primary key,
  nombre       text not null,
  razon_social text,
  nit          text,
  telefono     text,
  correo       text,
  dias_credito integer default 0,
  activo       boolean default true,
  creado       timestamptz default now()
);

create table if not exists public.cuentas_banco (
  id            bigint generated by default as identity primary key,
  nombre        text not null,
  banco         text,
  numero        text,
  tipo          text default 'monetaria'::text,
  moneda        text default 'GTQ'::text,
  saldo_inicial numeric default 0,
  activo        boolean default true,
  creada        timestamptz default now()
);

create table if not exists public.categorias (
  nombre       text not null primary key,
  umbral_stock numeric not null default 10
);

create table if not exists public.productos (
  id                bigint generated always as identity primary key,
  codigo            text not null,
  nombre            text not null,
  precio            numeric(12,2) default 0,
  costo             numeric(12,2) default 0,
  unidad            text default 'UNI'::text,
  stock             numeric(12,2) default 0,
  proveedor_ids     jsonb default '[]'::jsonb,
  sku_proveedor     text,
  nombre_proveedor  text,
  activo            boolean default true,
  creado            timestamptz default now(),
  tipo_empaque      text default 'unidad'::text,
  unidades_por_caja integer,
  stock_cajas       numeric(12,2) default 0,
  marca             text,
  precio_caja       numeric default 0,
  precio_unidad     numeric default 0,
  conversiones      jsonb default '[]'::jsonb,
  categoria         text
);

create table if not exists public.talonarios (
  id             bigint generated always as identity primary key,
  numero_inicial integer not null,
  numero_final   integer not null,
  cantidad       integer not null default 50,
  asignado_a     text,
  asignado_id    bigint,
  descripcion    text,
  estado         text default 'activo'::text,
  fecha_entrega  date default CURRENT_DATE,
  creado         timestamptz default now()
);


-- ── Clientes (se referencia a sí mismo por las sedes) ───────
create table if not exists public.clientes (
  id                  bigint generated always as identity primary key,
  nit                 text not null default 'CF'::text,
  nombre              text not null,
  razon_social        text,
  direccion           text,
  email               text,
  tiempo_credito      integer default 0,
  vendedor_id         bigint references public.vendedores(id) on delete set null,
  sedes_de            bigint references public.clientes(id) on delete set null,
  contacto_pagos      jsonb default '{}'::jsonb,
  contacto_compras    jsonb default '{}'::jsonb,
  precios             jsonb default '{}'::jsonb,
  activo              boolean default true,
  creado              timestamptz default now(),
  direccion_entrega   text,
  fecha_alta          date,
  nits_secundarios    jsonb default '[]'::jsonb,
  cobro_info          jsonb default '{}'::jsonb,
  seguimientos        jsonb default '[]'::jsonb,
  sub_vendedor_nombre text,
  ruta                text
);


-- ── Documentos y su cobranza ────────────────────────────────
create table if not exists public.documentos (
  id                  bigint generated always as identity primary key,
  numero              bigint,
  tipo_doc            text not null,
  cliente_id          bigint references public.clientes(id),
  cliente_nombre      text,
  cliente_comercial   text,
  cliente_nit         text,
  vendedor_id         bigint references public.vendedores(id) on delete set null,
  vendedor_nombre     text,
  items               jsonb not null default '[]'::jsonb,
  totales             jsonb not null default '{}'::jsonb,
  estado              text default 'abierto'::text,
  estado_pago         text default 'pendiente'::text,
  inventario_rebajado boolean default false,
  autorizacion        text,
  serie               text,
  numero_dte          text,
  orden_compra        text,
  dias_credito        integer default 0,
  vencimiento         timestamptz,
  exenta              boolean default false,
  escenario_exenta    text,
  piloto_id           bigint references public.pilotos(id) on delete set null,
  orden_ruta          integer,
  estado_entrega      text default 'sin'::text,
  entrega_info        jsonb,
  anulado             boolean default false,
  motivo_anulacion    text,
  creada              timestamptz default now(),
  pdf_base64          text,
  xml_base64          text,
  fecha_certificacion text,
  sub_vendedor_nombre text,
  factura_origen_id   bigint,
  nit_facturado       text,
  nombre_facturado    text,
  nota_interna        text,
  observaciones       text,
  anulado_fecha       text,
  anulado_por         text,
  sede                text,
  costo_historico     numeric
);

create table if not exists public.abonos (
  id                bigint generated always as identity primary key,
  documento_id      bigint references public.documentos(id) on delete cascade,
  fecha             date default CURRENT_DATE,
  monto             numeric(12,2) not null,
  metodo            text,
  referencia        text,
  no_recibo         text,
  comprobante       text,
  registrado_por    text,
  registrado_el     timestamptz default now(),
  anulado           boolean default false,
  motivo_anulacion  text,
  origen_cobro_ruta bigint,
  creado            timestamptz default now(),
  cuenta_banco_id   bigint references public.cuentas_banco(id)
);

create table if not exists public.cobros_ruta (
  id                bigint generated always as identity primary key,
  documento_id      bigint references public.documentos(id) on delete cascade,
  doc_num           text,
  cliente           text,
  monto             numeric(12,2) not null,
  modo              text,
  no_boleta         text,
  no_recibo         text,
  cheque            text,
  banco             text,
  piloto            text,
  fecha             timestamptz default now(),
  estado            text default 'cobrado'::text,
  depositado_fecha  timestamptz,
  recibido_por      text,
  recibido_fecha    timestamptz,
  procesado_por     text,
  procesado_fecha   timestamptz
);


-- ── Compras y pagos a proveedores ───────────────────────────
create table if not exists public.compras (
  id               bigint generated always as identity primary key,
  proveedor_id     bigint references public.proveedores(id),
  proveedor_nombre text,
  items            jsonb not null default '[]'::jsonb,
  total            numeric(12,2) default 0,
  fecha            timestamptz default now(),
  estado_recepcion text default 'pendiente'::text,
  facturada        boolean default false,
  doc_prov         text,
  tipo_pago        text default 'contado'::text,
  dias_credito     integer default 0,
  vencimiento      timestamptz,
  especial         boolean default false,
  oficializada     boolean default true,
  anulado          boolean default false,
  motivo_anulacion text,
  creada           timestamptz default now(),
  mes              text
);

create table if not exists public.pagos_proveedor (
  id               bigint generated always as identity primary key,
  compra_id        bigint references public.compras(id) on delete cascade,
  fecha            date default CURRENT_DATE,
  monto            numeric(12,2) not null,
  metodo           text,
  referencia       text,
  no_recibo        text,
  comprobante      text,
  registrado_por   text,
  registrado_el    timestamptz default now(),
  anulado          boolean default false,
  motivo_anulacion text,
  es_cierre        boolean default false,
  creado           timestamptz default now(),
  cuenta_banco_id  bigint references public.cuentas_banco(id)
);


-- ── Cotizaciones y créditos del cliente ─────────────────────
create table if not exists public.cotizaciones (
  id                   bigint generated always as identity primary key,
  numero               integer,
  cliente_id           bigint,
  cliente_nombre       text,
  cliente_comercial    text,
  cliente_nit          text,
  vendedor_id          bigint,
  vendedor_nombre      text,
  items                jsonb default '[]'::jsonb,
  totales              jsonb default '{}'::jsonb,
  observaciones        text,
  validez_dias         integer default 15,
  fecha_vence          date,
  estado               text default 'borrador'::text,
  creado_por           text,
  creada               timestamptz default now(),
  convertido_pedido_id bigint,
  vendedor_tel         text,
  vendedor_email       text,
  cliente_contacto     text,
  cliente_tel          text,
  cliente_email        text
);

create table if not exists public.creditos_cliente (
  id               bigint generated by default as identity primary key,
  cliente_id       bigint,
  tipo             text not null default 'ingreso'::text,
  monto            numeric not null default 0,
  fecha            date,
  documento_id     bigint,
  no_recibo        text,
  metodo           text,
  referencia       text,
  cuenta_banco_id  bigint,
  concepto         text,
  registrado_por   text,
  registrado_el    timestamptz default now(),
  anulado          boolean default false,
  motivo_anulacion text
);


-- ── Bancos ──────────────────────────────────────────────────
create table if not exists public.movimientos_banco (
  id                bigint generated by default as identity primary key,
  cuenta_id         bigint references public.cuentas_banco(id),
  fecha             date not null default CURRENT_DATE,
  tipo              text not null,
  monto             numeric not null,
  concepto          text,
  categoria         text,
  origen            text,
  origen_id         bigint,
  cuenta_destino_id bigint references public.cuentas_banco(id),
  referencia        text,
  registrado_por    text,
  registrado_el     timestamptz default now(),
  anulado           boolean default false,
  poliza            integer
);


-- ── Configuración, tareas, talonarios ───────────────────────
create table if not exists public.dashboard_config (
  rol    text not null primary key,
  config jsonb not null default '{}'::jsonb
);

create table if not exists public.recordatorios (
  id               bigint generated by default as identity primary key,
  titulo           text not null,
  nota             text,
  tipo             text not null default 'tarea'::text,
  ref_id           bigint,
  ref_label        text,
  fecha_vencimiento date,
  asignado_a       text,
  creado_por       text,
  prioridad        text default 'normal'::text,
  hecho            boolean default false,
  hecho_por        text,
  hecho_fecha      timestamptz,
  creado           timestamptz default now()
);

create table if not exists public.recibos_anulados (
  id           bigint generated always as identity primary key,
  numero       integer not null,
  talonario_id bigint references public.talonarios(id) on delete set null,
  motivo       text,
  anulado_por  text,
  fecha        timestamptz default now()
);


-- ── Roles y usuarios ────────────────────────────────────────
create table if not exists public.roles (
  rol               text not null primary key,
  label             text not null,
  views             jsonb not null default '[]'::jsonb,
  anular            boolean default false,
  facturar          boolean default false,
  crear_cliente     boolean default false,
  editar_inventario boolean default false,
  registrar_abono   boolean default false,
  readonly          boolean default false,
  compra_especial   boolean default false,
  asignar_piloto    boolean default false,
  convertir_cajas   boolean default false
);

create table if not exists public.usuarios (
  id             bigint generated always as identity primary key,
  auth_id        uuid references auth.users(id) on delete set null,
  nombre         text not null,
  correo         text unique,
  rol            text not null default 'ventas'::text,
  activo         boolean default true,
  vendedor_id    bigint references public.vendedores(id) on delete set null,
  piloto_id      bigint references public.pilotos(id) on delete set null,
  creado         timestamptz default now(),
  recibe_resumen boolean default false
);


-- ── Auditoría (bitácora encadenada) ─────────────────────────
create table if not exists public.auditoria (
  seq       bigint generated always as identity primary key,
  fecha     timestamptz default now(),
  usuario   text,
  rol       text,
  accion    text,
  detalle   text,
  prev_hash text,
  hash      text
);


-- ── Índices (los de rendimiento y el único de recibos) ──────
create index if not exists idx_abonos_documento        on public.abonos            (documento_id);
create index if not exists idx_clientes_nit            on public.clientes          (nit);
create index if not exists idx_clientes_vendedor       on public.clientes          (vendedor_id);
create index if not exists idx_cobros_ruta_estado      on public.cobros_ruta       (estado);
create index if not exists idx_compras_proveedor       on public.compras           (proveedor_id);
create index if not exists creditos_cliente_cliente_idx on public.creditos_cliente (cliente_id);
create index if not exists idx_documentos_cliente      on public.documentos        (cliente_id);
create index if not exists idx_documentos_estado       on public.documentos        (estado);
create index if not exists idx_documentos_piloto       on public.documentos        (piloto_id);
create index if not exists idx_documentos_tipo         on public.documentos        (tipo_doc);
create index if not exists idx_mov_cuenta              on public.movimientos_banco (cuenta_id);
create index if not exists idx_mov_fecha               on public.movimientos_banco (fecha);
create index if not exists idx_pagos_compra            on public.pagos_proveedor   (compra_id);
create unique index if not exists idx_recibos_anulados_numero on public.recibos_anulados (numero);
create index if not exists idx_talonarios_rango        on public.talonarios        (numero_inicial, numero_final);
