-- ============================================================
-- SEFE · Saldo a favor del cliente (creditos_cliente) — versión multiempresa
-- ============================================================
-- Reemplaza/complementa 20260820130000_creditos_cliente.sql (que nunca se
-- aplicó en Producción y era anterior al multiempresa). Crea la tabla con
-- la columna 'empresa' que el código ya usa, más RLS y el grant.
-- Al existir esta tabla, el navegador enciende solo el interruptor
-- _saldoFavorTabla y habilita el sobrepago (el excedente queda a favor).
-- Seguro de correr de más (if not exists / add column if not exists).
-- ============================================================

create table if not exists public.creditos_cliente (
  id            bigint generated by default as identity primary key,
  cliente_id    bigint,
  tipo          text not null default 'ingreso',   -- 'ingreso' | 'aplicacion'
  monto         numeric not null default 0,
  fecha         date,
  documento_id  bigint,
  no_recibo     text,
  metodo        text,
  referencia    text,
  cuenta_banco_id bigint,
  concepto      text,
  registrado_por text,
  registrado_el timestamptz default now(),
  anulado       boolean default false,
  motivo_anulacion text,
  empresa       text not null default 'SEFE'
);

-- Por si la tabla ya existía de una corrida vieja sin la columna.
alter table public.creditos_cliente
  add column if not exists empresa text not null default 'SEFE';

create index if not exists creditos_cliente_cliente_idx on public.creditos_cliente (cliente_id);

-- ── RLS: misma regla que las demás tablas operativas ──────────
alter table public.creditos_cliente enable row level security;

drop policy if exists sefe_leer on public.creditos_cliente;
create policy sefe_leer on public.creditos_cliente
  for select to authenticated
  using ((select public.sefe_activo()));

drop policy if exists sefe_crear on public.creditos_cliente;
create policy sefe_crear on public.creditos_cliente
  for insert to authenticated
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_editar on public.creditos_cliente;
create policy sefe_editar on public.creditos_cliente
  for update to authenticated
  using ((select public.sefe_puede_escribir()))
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_borrar on public.creditos_cliente;
create policy sefe_borrar on public.creditos_cliente
  for delete to authenticated
  using ((select public.sefe_es_admin()));

grant select, insert, update, delete on public.creditos_cliente to authenticated;
