-- ============================================================
-- SEFE · Saldo a favor del cliente (creditos_cliente)
-- ============================================================
-- Cuando un cliente deposita de más (o paga por adelantado), el
-- excedente queda como CRÉDITO a su favor y se puede aplicar a una
-- factura futura. Esta tabla es el libro de ese saldo a favor:
--
--   tipo = 'ingreso'     → entra saldo a favor (sobrepago / anticipo)
--   tipo = 'aplicacion'  → se usa saldo a favor en una factura
--
-- Saldo a favor del cliente = Σ(ingreso) − Σ(aplicacion), sin anulados.
--
-- Seguro de correr de más: todo es 'if not exists' / 'drop ... if exists'.
-- El RLS reutiliza las funciones sefe_* de la migración de seguridad.
-- ============================================================

create table if not exists public.creditos_cliente (
  id            bigint generated by default as identity primary key,
  cliente_id    bigint,
  tipo          text not null default 'ingreso',   -- 'ingreso' | 'aplicacion'
  monto         numeric not null default 0,
  fecha         date,
  documento_id  bigint,                             -- factura de origen (ingreso) o donde se aplicó (aplicacion)
  no_recibo     text,
  metodo        text,
  referencia    text,
  cuenta_banco_id bigint,
  concepto      text,
  registrado_por text,
  registrado_el timestamptz default now(),
  anulado       boolean default false,
  motivo_anulacion text
);

create index if not exists creditos_cliente_cliente_idx on public.creditos_cliente (cliente_id);

-- ── RLS: misma regla que las tablas operativas ──────────────
--   leer     → cualquier usuario activo
--   escribir → usuario activo que no sea sólo lectura
--   borrar   → sólo admin (casi nada se borra: se anula, que es UPDATE)
alter table public.creditos_cliente enable row level security;

drop policy if exists sefe_leer on public.creditos_cliente;
create policy sefe_leer on public.creditos_cliente
  for select to authenticated
  using ((select public.sefe_activo()));

drop policy if exists sefe_crear on public.creditos_cliente;
create policy sefe_crear on public.creditos_cliente
  for insert to authenticated
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_editar on public.creditos_cliente;
create policy sefe_editar on public.creditos_cliente
  for update to authenticated
  using ((select public.sefe_puede_escribir()))
  with check ((select public.sefe_puede_escribir()));

drop policy if exists sefe_borrar on public.creditos_cliente;
create policy sefe_borrar on public.creditos_cliente
  for delete to authenticated
  using ((select public.sefe_es_admin()));
